version: '3.8'

services:
  room-manager:
    image: isdockero/onliver-web-v1:latest
    networks:
      - service-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  service-network:
    external: true
