version: '3.8'

services:
  web-app:
    image: isdockero/onliver-web-v1:latest
    networks:
      - service-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  service-network:
    external: true
